export const filters = [
  {
    base: "bra",
    sizes: [
      "65A",
      "65B",
      "65C",
      "65D",
      "65E",
      "65F",
      "65G",
      "65H",
      "65I",
      "65J",
      "70A",
      "70B",
      "70C",
      "70D",
      "70E",
      "70F",
      "70G",
      "70H",
      "70I",
      "70J",
      "75A",
      "75B",
      "75C",
      "75D",
      "75E",
      "75F",
      "75G",
      "75H",
      "75I",
      "75J",
      "75K",
      "75L",
      "80A",
      "80B",
      "80C",
      "80D",
      "80E",
      "80F",
      "80G",
      "80H",
      "80I",
      "80J",
      "80K",
      "80L",
      "85A",
      "85B",
      "85C",
      "85D",
      "85E",
      "85F",
      "85G",
      "85H",
      "85I",
      "85J",
      "85K",
      "85L",
      "90A",
      "90B",
      "90C",
      "90D",
      "90E",
      "90F",
      "90G",
      "90H",
      "90I",
      "90J",
      "90K",
      "90L",
      "95A",
      "95B",
      "95C",
      "95D",
      "95E",
      "95F",
      "95G",
      "95H",
      "95I",
      "95J",
      "95K",
      "95L",
      "100A",
      "100B",
      "100C",
      "100D",
      "100E",
      "100F",
      "105D",
      "105E",
    ],

    brands: ["AVA", "GORSENIA", "GAIA", "MAT", "NIPPLEX"],
    types: [
      { value: "yshilneni", label: "Ущільнені" },
      { value: "soft", label: "М'які" },
      { value: "push", label: "Push-ups" },
      { value: "napivyshilneni", label: "Напівщільні" },
    ],
  },
  {
    base: "womunderwear",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    brands: ["AVA", "GORSENIA", "GAIA", "WOLBAR", "LAMA", "KEY"],
    types: [
      { value: "braz", label: "Бразиліана" },
      { value: "slip", label: "Сліпи" },
      { value: "bikini", label: "Бікіні" },
      { value: "strings", label: "Стрінги" },
    ],
  },
  {
    base: "pijamas, robe, nightgowns",
    sizes: [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL",
      "4XL",
      "5XL",
      "6XL",
      "36",
      "38",
      "40",
      "42",
      "44",
      "46",
      "48",
      "50",
      "52",
    ],
    brands: [
      "CORNETTE",
      "BABELL",
      "DE LAFENSE",
      "DKAREN",
      "KEY",
      "TARO",
      "DOROTA",
    ],
  },
  {
    base: "corrunderwear",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL", "6XL"],
    brands: ["ELDAR", "GORSENIA", "MITEX", "WOLBAR"],
    types: [
      { value: "pants", label: "Труси" },
      { value: "cors", label: "Корсети" },
      { value: "comb", label: "Комбінації, боді, плаття" },
    ],
  },
  {
    base: "manunderwear, manshirt",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    brands: ["KEY", "CORNETTE", "HENDERSON", "LAMA", "REDO"],
  },
  {
    base: "manpijamas, manrobe",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    brands: ["KEY", "CORNETTE", "HENDERSON", "TARO", "REGINA", "L&L"],
  },
  {
    base: "womswimsuit",
    sizes: [
      "S",
      "M",
      "L",
      "XL",
      "2XL",
      "3XL",
      "4XL",
      "5XL",
      "65A",
      "65B",
      "65C",
      "65D",
      "65E",
      "65F",
      "65G",
      "65H",
      "65I",
      "65J",
      "70A",
      "70B",
      "70C",
      "70D",
      "70E",
      "70F",
      "70G",
      "70H",
      "70I",
      "70J",
      "75A",
      "75B",
      "75C",
      "75D",
      "75E",
      "75F",
      "75G",
      "75H",
      "75I",
      "75J",
      "75K",
      "75L",
      "80A",
      "80B",
      "80C",
      "80D",
      "80E",
      "80F",
      "80G",
      "80H",
      "80I",
      "80J",
      "80K",
      "80L",
      "85A",
      "85B",
      "85C",
      "85D",
      "85E",
      "85F",
      "85G",
      "85H",
      "85I",
      "85J",
      "85K",
      "85L",
      "90A",
      "90B",
      "90C",
      "90D",
      "90E",
      "90F",
      "90G",
      "90H",
      "90I",
      "90J",
      "90K",
      "90L",
      "95A",
      "95B",
      "95C",
      "95D",
      "95E",
      "95F",
      "95G",
      "95H",
      "95I",
      "95J",
      "95K",
      "95L",
      "100A",
      "100B",
      "100C",
      "100D",
      "100E",
      "100F",
      "105D",
      "105E",
    ],
    brands: ["AVA", "SELF", "MEDIALONO"],
  },
  {
    base: "manswimsuit",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    brands: ["AVA", "SELF", "MEDIALONO"],
  },
  {
    base: "news, sale",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL", "6XL"],
    types: [
      { value: "bra", label: "Бюстгальтери" },
      { value: "pants", label: "Труси" },
      { value: "pijamas", label: "Піжами" },
      { value: "robe", label: "Халати" },
      { value: "nightgowns", label: "Нічні сорочки" },
    ],
  },
];
